package com.mcip.nia.orb;
/**
<p>
<ul>
<li> <b>Java Class</b> com.mcip.nia.orb.PlyEdrAppInfoHelper
<li> <b>Source File</b> com/mcip/nia/orb/PlyEdrAppInfoHelper.java
<li> <b>IDL Source File</b> policyInfoStruct.idl
<li> <b>IDL Absolute Name</b> ::com::mcip::nia::orb::PlyEdrAppInfo
<li> <b>Repository Identifier</b> IDL:com/mcip/nia/orb/PlyEdrAppInfo:1.0
</ul>
<b>IDL definition:</b>
<pre>
    #pragma prefix "com/mcip/nia/orb"
    struct PlyEdrAppInfo {
      wstring c_crt_cde;
      wstring c_crt_tm;
      wstring c_upd_cde;
      wstring c_upd_tm;
      wstring c_edr_app_no;
      wstring c_edr_no;
      wstring c_ply_no;
      wstring c_edr_typ;
      wstring c_app_prsn_no;
      wstring c_app_prsn_nme;
      wstring c_app_prsn_addr;
      wstring c_app_prsn_tel;
      wstring t_edr_app_tm;
      wstring c_edr_rsn;
      wstring c_edr_ctnt;
      wstring n_amt_var;
      wstring n_prm_var;
      wstring n_nclm_amt;
      wstring n_appnt_amt;
      wstring n_ndis_amt;
      wstring n_nnclm_amt;
      wstring c_orig_ply_no;
      wstring c_dpt_cde;
      wstring c_bsns_typ;
      wstring c_cmpny_agt_cde;
      wstring n_sub_co_no;
      wstring c_agt_agr_no;
      wstring c_brkr_cde;
      wstring c_sls_cde;
      wstring c_insrnc_cmpny_cde;
      wstring c_insrnt_cde;
      wstring c_insrnt_nme;
      wstring c_insrnt_addr;
      wstring c_bnfc_cde;
      wstring c_bnfc_nme;
      wstring c_app_cde;
      wstring c_app_nme;
      wstring c_app_addr;
      wstring c_app_tel;
      wstring c_insrnc_cde;
      wstring c_claus_cde;
      wstring t_app_tm;
      wstring t_insrnc_bgn_tm;
      wstring t_insrnc_end_tm;
      wstring t_sign_tm;
      wstring c_amt_cur;
      wstring n_insrnc_vlu;
      wstring n_amt;
      wstring n_rate;
      wstring n_prm;
      wstring n_rdr_prm;
      wstring n_sum_prm;
      wstring c_prm_cur;
      wstring n_nclm_prop;
      wstring n_appnt_prop;
      wstring n_cmm_prop;
      wstring n_brk_prop;
      wstring n_pay_tms;
      wstring c_appnt;
      wstring c_remark;
      wstring c_crt_prsn;
      wstring c_undr_prsn;
      wstring t_undr_tm;
      wstring c_rinsrnc_mrk;
      wstring c_coinsrnc_mrk;
      wstring t_input_tm;
      wstring c_undr_dpt;
      wstring c_opr_typ;
      wstring c_edr_prj_no;
      wstring t_next_edr_undr_tm;
      wstring c_dpt_cnm;
      wstring c_insrnc_cnm;
      wstring c_undr_prsn_cnm;
      wstring c_undr_dpt_cnm;
      wstring c_crt_prsn_cnm;
      wstring c_sls_nme;
      wstring c_cmpny_agt_nme;
      wstring c_amt_cur_cnm;
      wstring c_agelong_mrk;
      wstring c_ceprn_mrk;
      wstring c_udr_mrk;
      wstring c_salegrp_cde;
      wstring n_got_prm;
      wstring c_sum_nclm;
      wstring c_zip_cde;
      wstring c_sttl;
      wstring c_ratio;
      wstring c_cntct_prsn_nme;
      wstring c_app_typ;
      wstring c_query_mrk;
      wstring c_fst_undr_prsn;
      wstring c_fst_opn;
      wstring c_chk_prsn;
      wstring c_chk_rec;
      wstring c_chk_tm;
      wstring c_fst_undr_tm;
      wstring n_save_amt_var;
      wstring c_open_cover_no;
      wstring c_internet_typ;
    };
</pre>
</p>
*/
abstract public class PlyEdrAppInfoHelper {
  private static org.omg.CORBA.ORB _orb() {
    return org.omg.CORBA.ORB.init();
  }
  public static com.mcip.nia.orb.PlyEdrAppInfo read(org.omg.CORBA.portable.InputStream _input) {
    com.mcip.nia.orb.PlyEdrAppInfo result = new com.mcip.nia.orb.PlyEdrAppInfo();
    result.c_crt_cde = _input.read_wstring();
    result.c_crt_tm = _input.read_wstring();
    result.c_upd_cde = _input.read_wstring();
    result.c_upd_tm = _input.read_wstring();
    result.c_edr_app_no = _input.read_wstring();
    result.c_edr_no = _input.read_wstring();
    result.c_ply_no = _input.read_wstring();
    result.c_edr_typ = _input.read_wstring();
    result.c_app_prsn_no = _input.read_wstring();
    result.c_app_prsn_nme = _input.read_wstring();
    result.c_app_prsn_addr = _input.read_wstring();
    result.c_app_prsn_tel = _input.read_wstring();
    result.t_edr_app_tm = _input.read_wstring();
    result.c_edr_rsn = _input.read_wstring();
    result.c_edr_ctnt = _input.read_wstring();
    result.n_amt_var = _input.read_wstring();
    result.n_prm_var = _input.read_wstring();
    result.n_nclm_amt = _input.read_wstring();
    result.n_appnt_amt = _input.read_wstring();
    result.n_ndis_amt = _input.read_wstring();
    result.n_nnclm_amt = _input.read_wstring();
    result.c_orig_ply_no = _input.read_wstring();
    result.c_dpt_cde = _input.read_wstring();
    result.c_bsns_typ = _input.read_wstring();
    result.c_cmpny_agt_cde = _input.read_wstring();
    result.n_sub_co_no = _input.read_wstring();
    result.c_agt_agr_no = _input.read_wstring();
    result.c_brkr_cde = _input.read_wstring();
    result.c_sls_cde = _input.read_wstring();
    result.c_insrnc_cmpny_cde = _input.read_wstring();
    result.c_insrnt_cde = _input.read_wstring();
    result.c_insrnt_nme = _input.read_wstring();
    result.c_insrnt_addr = _input.read_wstring();
    result.c_bnfc_cde = _input.read_wstring();
    result.c_bnfc_nme = _input.read_wstring();
    result.c_app_cde = _input.read_wstring();
    result.c_app_nme = _input.read_wstring();
    result.c_app_addr = _input.read_wstring();
    result.c_app_tel = _input.read_wstring();
    result.c_insrnc_cde = _input.read_wstring();
    result.c_claus_cde = _input.read_wstring();
    result.t_app_tm = _input.read_wstring();
    result.t_insrnc_bgn_tm = _input.read_wstring();
    result.t_insrnc_end_tm = _input.read_wstring();
    result.t_sign_tm = _input.read_wstring();
    result.c_amt_cur = _input.read_wstring();
    result.n_insrnc_vlu = _input.read_wstring();
    result.n_amt = _input.read_wstring();
    result.n_rate = _input.read_wstring();
    result.n_prm = _input.read_wstring();
    result.n_rdr_prm = _input.read_wstring();
    result.n_sum_prm = _input.read_wstring();
    result.c_prm_cur = _input.read_wstring();
    result.n_nclm_prop = _input.read_wstring();
    result.n_appnt_prop = _input.read_wstring();
    result.n_cmm_prop = _input.read_wstring();
    result.n_brk_prop = _input.read_wstring();
    result.n_pay_tms = _input.read_wstring();
    result.c_appnt = _input.read_wstring();
    result.c_remark = _input.read_wstring();
    result.c_crt_prsn = _input.read_wstring();
    result.c_undr_prsn = _input.read_wstring();
    result.t_undr_tm = _input.read_wstring();
    result.c_rinsrnc_mrk = _input.read_wstring();
    result.c_coinsrnc_mrk = _input.read_wstring();
    result.t_input_tm = _input.read_wstring();
    result.c_undr_dpt = _input.read_wstring();
    result.c_opr_typ = _input.read_wstring();
    result.c_edr_prj_no = _input.read_wstring();
    result.t_next_edr_undr_tm = _input.read_wstring();
    result.c_dpt_cnm = _input.read_wstring();
    result.c_insrnc_cnm = _input.read_wstring();
    result.c_undr_prsn_cnm = _input.read_wstring();
    result.c_undr_dpt_cnm = _input.read_wstring();
    result.c_crt_prsn_cnm = _input.read_wstring();
    result.c_sls_nme = _input.read_wstring();
    result.c_cmpny_agt_nme = _input.read_wstring();
    result.c_amt_cur_cnm = _input.read_wstring();
    result.c_agelong_mrk = _input.read_wstring();
    result.c_ceprn_mrk = _input.read_wstring();
    result.c_udr_mrk = _input.read_wstring();
    result.c_salegrp_cde = _input.read_wstring();
    result.n_got_prm = _input.read_wstring();
    result.c_sum_nclm = _input.read_wstring();
    result.c_zip_cde = _input.read_wstring();
    result.c_sttl = _input.read_wstring();
    result.c_ratio = _input.read_wstring();
    result.c_cntct_prsn_nme = _input.read_wstring();
    result.c_app_typ = _input.read_wstring();
    result.c_query_mrk = _input.read_wstring();
    result.c_fst_undr_prsn = _input.read_wstring();
    result.c_fst_opn = _input.read_wstring();
    result.c_chk_prsn = _input.read_wstring();
    result.c_chk_rec = _input.read_wstring();
    result.c_chk_tm = _input.read_wstring();
    result.c_fst_undr_tm = _input.read_wstring();
    result.n_save_amt_var = _input.read_wstring();
    result.c_open_cover_no = _input.read_wstring();
    result.c_internet_typ = _input.read_wstring();
    return result;
  }
  public static void write(org.omg.CORBA.portable.OutputStream _output, com.mcip.nia.orb.PlyEdrAppInfo value) {
    _output.write_wstring(value.c_crt_cde);
    _output.write_wstring(value.c_crt_tm);
    _output.write_wstring(value.c_upd_cde);
    _output.write_wstring(value.c_upd_tm);
    _output.write_wstring(value.c_edr_app_no);
    _output.write_wstring(value.c_edr_no);
    _output.write_wstring(value.c_ply_no);
    _output.write_wstring(value.c_edr_typ);
    _output.write_wstring(value.c_app_prsn_no);
    _output.write_wstring(value.c_app_prsn_nme);
    _output.write_wstring(value.c_app_prsn_addr);
    _output.write_wstring(value.c_app_prsn_tel);
    _output.write_wstring(value.t_edr_app_tm);
    _output.write_wstring(value.c_edr_rsn);
    _output.write_wstring(value.c_edr_ctnt);
    _output.write_wstring(value.n_amt_var);
    _output.write_wstring(value.n_prm_var);
    _output.write_wstring(value.n_nclm_amt);
    _output.write_wstring(value.n_appnt_amt);
    _output.write_wstring(value.n_ndis_amt);
    _output.write_wstring(value.n_nnclm_amt);
    _output.write_wstring(value.c_orig_ply_no);
    _output.write_wstring(value.c_dpt_cde);
    _output.write_wstring(value.c_bsns_typ);
    _output.write_wstring(value.c_cmpny_agt_cde);
    _output.write_wstring(value.n_sub_co_no);
    _output.write_wstring(value.c_agt_agr_no);
    _output.write_wstring(value.c_brkr_cde);
    _output.write_wstring(value.c_sls_cde);
    _output.write_wstring(value.c_insrnc_cmpny_cde);
    _output.write_wstring(value.c_insrnt_cde);
    _output.write_wstring(value.c_insrnt_nme);
    _output.write_wstring(value.c_insrnt_addr);
    _output.write_wstring(value.c_bnfc_cde);
    _output.write_wstring(value.c_bnfc_nme);
    _output.write_wstring(value.c_app_cde);
    _output.write_wstring(value.c_app_nme);
    _output.write_wstring(value.c_app_addr);
    _output.write_wstring(value.c_app_tel);
    _output.write_wstring(value.c_insrnc_cde);
    _output.write_wstring(value.c_claus_cde);
    _output.write_wstring(value.t_app_tm);
    _output.write_wstring(value.t_insrnc_bgn_tm);
    _output.write_wstring(value.t_insrnc_end_tm);
    _output.write_wstring(value.t_sign_tm);
    _output.write_wstring(value.c_amt_cur);
    _output.write_wstring(value.n_insrnc_vlu);
    _output.write_wstring(value.n_amt);
    _output.write_wstring(value.n_rate);
    _output.write_wstring(value.n_prm);
    _output.write_wstring(value.n_rdr_prm);
    _output.write_wstring(value.n_sum_prm);
    _output.write_wstring(value.c_prm_cur);
    _output.write_wstring(value.n_nclm_prop);
    _output.write_wstring(value.n_appnt_prop);
    _output.write_wstring(value.n_cmm_prop);
    _output.write_wstring(value.n_brk_prop);
    _output.write_wstring(value.n_pay_tms);
    _output.write_wstring(value.c_appnt);
    _output.write_wstring(value.c_remark);
    _output.write_wstring(value.c_crt_prsn);
    _output.write_wstring(value.c_undr_prsn);
    _output.write_wstring(value.t_undr_tm);
    _output.write_wstring(value.c_rinsrnc_mrk);
    _output.write_wstring(value.c_coinsrnc_mrk);
    _output.write_wstring(value.t_input_tm);
    _output.write_wstring(value.c_undr_dpt);
    _output.write_wstring(value.c_opr_typ);
    _output.write_wstring(value.c_edr_prj_no);
    _output.write_wstring(value.t_next_edr_undr_tm);
    _output.write_wstring(value.c_dpt_cnm);
    _output.write_wstring(value.c_insrnc_cnm);
    _output.write_wstring(value.c_undr_prsn_cnm);
    _output.write_wstring(value.c_undr_dpt_cnm);
    _output.write_wstring(value.c_crt_prsn_cnm);
    _output.write_wstring(value.c_sls_nme);
    _output.write_wstring(value.c_cmpny_agt_nme);
    _output.write_wstring(value.c_amt_cur_cnm);
    _output.write_wstring(value.c_agelong_mrk);
    _output.write_wstring(value.c_ceprn_mrk);
    _output.write_wstring(value.c_udr_mrk);
    _output.write_wstring(value.c_salegrp_cde);
    _output.write_wstring(value.n_got_prm);
    _output.write_wstring(value.c_sum_nclm);
    _output.write_wstring(value.c_zip_cde);
    _output.write_wstring(value.c_sttl);
    _output.write_wstring(value.c_ratio);
    _output.write_wstring(value.c_cntct_prsn_nme);
    _output.write_wstring(value.c_app_typ);
    _output.write_wstring(value.c_query_mrk);
    _output.write_wstring(value.c_fst_undr_prsn);
    _output.write_wstring(value.c_fst_opn);
    _output.write_wstring(value.c_chk_prsn);
    _output.write_wstring(value.c_chk_rec);
    _output.write_wstring(value.c_chk_tm);
    _output.write_wstring(value.c_fst_undr_tm);
    _output.write_wstring(value.n_save_amt_var);
    _output.write_wstring(value.c_open_cover_no);
    _output.write_wstring(value.c_internet_typ);
  }
  public static void insert(org.omg.CORBA.Any any, com.mcip.nia.orb.PlyEdrAppInfo value) {
    org.omg.CORBA.portable.OutputStream output = any.create_output_stream();
    write(output, value);
    any.read_value(output.create_input_stream(), type());
  }
  public static com.mcip.nia.orb.PlyEdrAppInfo extract(org.omg.CORBA.Any any) {
    if(!any.type().equal(type())) {
      throw new org.omg.CORBA.BAD_TYPECODE();
    }
    return read(any.create_input_stream());
  }
  private static org.omg.CORBA.TypeCode _type;
  public static org.omg.CORBA.TypeCode type() {
    if(_type == null) {
      org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[99];
      members[0] = new org.omg.CORBA.StructMember("c_crt_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[1] = new org.omg.CORBA.StructMember("c_crt_tm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[2] = new org.omg.CORBA.StructMember("c_upd_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[3] = new org.omg.CORBA.StructMember("c_upd_tm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[4] = new org.omg.CORBA.StructMember("c_edr_app_no", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[5] = new org.omg.CORBA.StructMember("c_edr_no", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[6] = new org.omg.CORBA.StructMember("c_ply_no", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[7] = new org.omg.CORBA.StructMember("c_edr_typ", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[8] = new org.omg.CORBA.StructMember("c_app_prsn_no", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[9] = new org.omg.CORBA.StructMember("c_app_prsn_nme", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[10] = new org.omg.CORBA.StructMember("c_app_prsn_addr", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[11] = new org.omg.CORBA.StructMember("c_app_prsn_tel", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[12] = new org.omg.CORBA.StructMember("t_edr_app_tm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[13] = new org.omg.CORBA.StructMember("c_edr_rsn", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[14] = new org.omg.CORBA.StructMember("c_edr_ctnt", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[15] = new org.omg.CORBA.StructMember("n_amt_var", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[16] = new org.omg.CORBA.StructMember("n_prm_var", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[17] = new org.omg.CORBA.StructMember("n_nclm_amt", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[18] = new org.omg.CORBA.StructMember("n_appnt_amt", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[19] = new org.omg.CORBA.StructMember("n_ndis_amt", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[20] = new org.omg.CORBA.StructMember("n_nnclm_amt", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[21] = new org.omg.CORBA.StructMember("c_orig_ply_no", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[22] = new org.omg.CORBA.StructMember("c_dpt_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[23] = new org.omg.CORBA.StructMember("c_bsns_typ", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[24] = new org.omg.CORBA.StructMember("c_cmpny_agt_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[25] = new org.omg.CORBA.StructMember("n_sub_co_no", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[26] = new org.omg.CORBA.StructMember("c_agt_agr_no", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[27] = new org.omg.CORBA.StructMember("c_brkr_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[28] = new org.omg.CORBA.StructMember("c_sls_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[29] = new org.omg.CORBA.StructMember("c_insrnc_cmpny_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[30] = new org.omg.CORBA.StructMember("c_insrnt_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[31] = new org.omg.CORBA.StructMember("c_insrnt_nme", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[32] = new org.omg.CORBA.StructMember("c_insrnt_addr", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[33] = new org.omg.CORBA.StructMember("c_bnfc_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[34] = new org.omg.CORBA.StructMember("c_bnfc_nme", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[35] = new org.omg.CORBA.StructMember("c_app_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[36] = new org.omg.CORBA.StructMember("c_app_nme", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[37] = new org.omg.CORBA.StructMember("c_app_addr", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[38] = new org.omg.CORBA.StructMember("c_app_tel", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[39] = new org.omg.CORBA.StructMember("c_insrnc_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[40] = new org.omg.CORBA.StructMember("c_claus_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[41] = new org.omg.CORBA.StructMember("t_app_tm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[42] = new org.omg.CORBA.StructMember("t_insrnc_bgn_tm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[43] = new org.omg.CORBA.StructMember("t_insrnc_end_tm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[44] = new org.omg.CORBA.StructMember("t_sign_tm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[45] = new org.omg.CORBA.StructMember("c_amt_cur", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[46] = new org.omg.CORBA.StructMember("n_insrnc_vlu", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[47] = new org.omg.CORBA.StructMember("n_amt", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[48] = new org.omg.CORBA.StructMember("n_rate", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[49] = new org.omg.CORBA.StructMember("n_prm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[50] = new org.omg.CORBA.StructMember("n_rdr_prm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[51] = new org.omg.CORBA.StructMember("n_sum_prm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[52] = new org.omg.CORBA.StructMember("c_prm_cur", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[53] = new org.omg.CORBA.StructMember("n_nclm_prop", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[54] = new org.omg.CORBA.StructMember("n_appnt_prop", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[55] = new org.omg.CORBA.StructMember("n_cmm_prop", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[56] = new org.omg.CORBA.StructMember("n_brk_prop", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[57] = new org.omg.CORBA.StructMember("n_pay_tms", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[58] = new org.omg.CORBA.StructMember("c_appnt", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[59] = new org.omg.CORBA.StructMember("c_remark", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[60] = new org.omg.CORBA.StructMember("c_crt_prsn", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[61] = new org.omg.CORBA.StructMember("c_undr_prsn", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[62] = new org.omg.CORBA.StructMember("t_undr_tm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[63] = new org.omg.CORBA.StructMember("c_rinsrnc_mrk", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[64] = new org.omg.CORBA.StructMember("c_coinsrnc_mrk", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[65] = new org.omg.CORBA.StructMember("t_input_tm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[66] = new org.omg.CORBA.StructMember("c_undr_dpt", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[67] = new org.omg.CORBA.StructMember("c_opr_typ", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[68] = new org.omg.CORBA.StructMember("c_edr_prj_no", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[69] = new org.omg.CORBA.StructMember("t_next_edr_undr_tm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[70] = new org.omg.CORBA.StructMember("c_dpt_cnm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[71] = new org.omg.CORBA.StructMember("c_insrnc_cnm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[72] = new org.omg.CORBA.StructMember("c_undr_prsn_cnm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[73] = new org.omg.CORBA.StructMember("c_undr_dpt_cnm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[74] = new org.omg.CORBA.StructMember("c_crt_prsn_cnm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[75] = new org.omg.CORBA.StructMember("c_sls_nme", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[76] = new org.omg.CORBA.StructMember("c_cmpny_agt_nme", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[77] = new org.omg.CORBA.StructMember("c_amt_cur_cnm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[78] = new org.omg.CORBA.StructMember("c_agelong_mrk", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[79] = new org.omg.CORBA.StructMember("c_ceprn_mrk", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[80] = new org.omg.CORBA.StructMember("c_udr_mrk", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[81] = new org.omg.CORBA.StructMember("c_salegrp_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[82] = new org.omg.CORBA.StructMember("n_got_prm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[83] = new org.omg.CORBA.StructMember("c_sum_nclm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[84] = new org.omg.CORBA.StructMember("c_zip_cde", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[85] = new org.omg.CORBA.StructMember("c_sttl", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[86] = new org.omg.CORBA.StructMember("c_ratio", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[87] = new org.omg.CORBA.StructMember("c_cntct_prsn_nme", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[88] = new org.omg.CORBA.StructMember("c_app_typ", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[89] = new org.omg.CORBA.StructMember("c_query_mrk", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[90] = new org.omg.CORBA.StructMember("c_fst_undr_prsn", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[91] = new org.omg.CORBA.StructMember("c_fst_opn", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[92] = new org.omg.CORBA.StructMember("c_chk_prsn", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[93] = new org.omg.CORBA.StructMember("c_chk_rec", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[94] = new org.omg.CORBA.StructMember("c_chk_tm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[95] = new org.omg.CORBA.StructMember("c_fst_undr_tm", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[96] = new org.omg.CORBA.StructMember("n_save_amt_var", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[97] = new org.omg.CORBA.StructMember("c_open_cover_no", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      members[98] = new org.omg.CORBA.StructMember("c_internet_typ", _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_wstring), null);
      _type = (_orb()).create_struct_tc(id(), "PlyEdrAppInfo", members);
    }
    return _type;
  }
  public static java.lang.String id() {
    return "IDL:com/mcip/nia/orb/PlyEdrAppInfo:1.0";
  }
}
