/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InterGateway */

#ifndef _Included_InterGateway
#define _Included_InterGateway
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: ins */
/*
 * Class:     InterGateway
 * Method:    packetchanege
 * Signature: (I[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_InterGateway_packetchanege
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
