/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jtoc_JavaC */

#ifndef _Included_jtoc_JavaC
#define _Included_jtoc_JavaC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jtoc_JavaC
 * Method:    packetchanege
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jtoc_JavaC_packetchanege
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
